_BASE_: ../Base-MGN.yml

MODEL:
  BACKBONE:
    WITH_IBN: True

DATASETS:
  NAMES: ("WILDTRACK",)
  TESTS: ("WILDTRACK",)

DATAROOT: /mnt/sdb/dataset/MOT_datasets/CrossMOT_dataset/wildtrack/ReID_format/

OUTPUT_DIR: logs/WILDTRACK/mgn_R50-ibn
