_BASE_: ../Base-MGN.yml

MODEL:
  BACKBONE:
    WITH_IBN: True

DATASETS:
  NAMES: ("MM",)
  TESTS: ("MM",)

DATAROOT: /mnt/sdb/dataset/MOT_datasets/CrossMOT_dataset/MvMHAT/ReID_format/

OUTPUT_DIR: logs/MM/mgn_R50-ibn
