_BASE_: ../Base-MGN.yml

MODEL:
  BACKBONE:
    WITH_IBN: True

DATASETS:
  NAMES: ("DIVO",)
  TESTS: ("DIVO",)

DATAROOT: /mnt/sdb/syh/DIVOTrack/datasets/DIVO/images/dets/det_imgs/

OUTPUT_DIR: logs/DIVO/mgn_R50-ibn


